### ISSUE TITLE
Licensing of overlib

### ISSUE THREAD

**Issue by tillea** [overlib/overlib#2]
Hi Erik,

as a Debian maintainer I stumbled upon two projects (Qiime[1] and CGView[2]) that are shipping a copy of overlib.js in their source code. Since as a Debian maintainer I have the oblication to list all copyrights properly I stumbled upon the license agreement in overlib.js, saying

//\  This file might be old, always check for the latest version at:
//\  http://www.bosrup.com/web/overlib/
//\
//\  Please read the license agreement (available through the link above)
//\  before using overLIB.

The project obviously moved to Github but the license information did not and the page above is not available any more.

I hope that the license is DFSG free.

Kind regards and thanks for providing overlib.js

      Andreas.

[1] http://www.qiime.org/
[2] http://wishart.biology.ualberta.ca/cgview/

**Comment by vegantech** [comment]
Hello Andreas,
   I'm not in contact with Erik.  I just set this up as a place to share community fixes as I wasn't able to find a way to do so otherwise.     

I checked the Internet Archive.   He used the Artistic License Version 1, which is listed as DFSG compatible on https://wiki.debian.org/DFSGLicenses#The_Artistic_License.

http://web.archive.org/web/20140106173046/http://www.bosrup.com/web/overlib/?License

Thanks,
Shawn

I've updated the README.md to point to the opensource.org copy of the license.

**Comment by tillea** [comment]
Hi Shawn,

thanks a lot for the quick response

```
  Andreas.
```

On Fri, Nov 27, 2015 at 10:12:25AM -0800, Shawn Balestracci wrote:

> Hello Andreas,
>    I'm not in contact with Erik.  I just set this up as a place to share community fixes as I wasn't able to find a way to do so otherwise.     
> 
> I checked the Internet Archive.   He used the Artistic License Version 1, which is listed as DFSG compatible on https://wiki.debian.org/DFSGLicenses#The_Artistic_License.
> 
> http://web.archive.org/web/20140106173046/http://www.bosrup.com/web/overlib/?License
> 
> Thanks,
> Shawn
> 
> I've updated the README.md to point to the opensource.org copy of the license.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/overlib/overlib/issues/2#issuecomment-160184852

## 

http://fam-tille.de
